apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-app
  template:
    metadata:
      labels:
        app: server-app
    spec:
      containers:
      - name: server-app
        image: server-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9090
      - name: envoy
        image: envoyproxy/envoy:v1.25-latest
        args: ["-c", "/etc/envoy/envoy-bootstrap-server.yaml"]
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy
        - name: spire-socket
          mountPath: /run/spire/sockets
      volumes:
      - name: envoy-config
        configMap:
          name: envoy-bootstrap-server
      - name: spire-socket
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: server-app
spec:
  selector:
    app: server-app
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 9090
