apiVersion: v1
kind: ConfigMap
metadata:
  name: client-envoy-config
data:
  envoy.yaml: |
    node:
      id: spiffe://neutrino.org/ns/default/sa/client-envoy
      cluster: spiffe://neutrino.org/ns/default/sa/client-envoy
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address: { address: 0.0.0.0, port_value: 8282 }
        filter_chains:
        - filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains: ["*"]
                  routes:
                  - match: { prefix: "/" }
                    route: { cluster: server }
              http_filters:
              - name: envoy.filters.http.router
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
      - name: server
        type: STRICT_DNS
        connect_timeout: 1s
        load_assignment:
          cluster_name: server
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address:
                    address: server-app.default.svc.cluster.local
                    port_value: 8282
        transport_socket:
          name: envoy.transport_sockets.tls
          typed_config:
            "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.UpstreamTlsContext
            common_tls_context:
              tls_certificate_sds_secret_configs:
              - name: spiffe://neutrino.org/ns/default/sa/client-envoy
                sds_config:
                  api_config_source:
                    api_type: GRPC
                    transport_api_version: V3
                    grpc_services:
                      envoy_grpc:
                        cluster_name: spire_agent
              validation_context_sds_secret_config:
                name: spiffe://neutrino.org/ns/default/sa/client-envoy
                sds_config:
                  api_config_source:
                    api_type: GRPC
                    transport_api_version: V3  
                    grpc_services:
                      envoy_grpc:
                        cluster_name: spire_agent
      - name: spire_agent
        type: STATIC
        connect_timeout: 1s
        http2_protocol_options: {}
        load_assignment:
          cluster_name: spire_agent
          endpoints:
            - lb_endpoints:
                - endpoint:
                    address:
                      pipe:
                        path: /run/spire/sockets/agent.sock
    admin:
      access_log_path: "/tmp/admin_access.log"
      address:
        socket_address: { address: 0.0.0.0, port_value: 9901 }


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: server-envoy-config
data:
  envoy.yaml: |
    node:
      id: spiffe://neutrino.org/ns/default/sa/server-envoy
      cluster: spiffe://neutrino.org/ns/default/sa/server-envoy
    static_resources:
      listeners:
      - name: listener_0
        address:
          socket_address: { address: 0.0.0.0, port_value: 8282 }
        filter_chains:
        - transport_socket:
            name: envoy.transport_sockets.tls
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.transport_sockets.tls.v3.DownstreamTlsContext
              common_tls_context:
                tls_certificate_sds_secret_configs:
                - name: spiffe://neutrino.org/ns/default/sa/server-envoy
                  sds_config:
                    api_config_source:
                      api_type: GRPC
                      transport_api_version: V3
                      grpc_services:
                        envoy_grpc:
                          cluster_name: spire_agent
                validation_context_sds_secret_config:
                  name: spiffe://neutrino.org/ns/default/sa/server-envoy
                  sds_config:
                    api_config_source:
                      api_type: GRPC
                      transport_api_version: V3
                      grpc_services:
                        envoy_grpc:
                          cluster_name: spire_agent
          filters:
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: ingress_http
              route_config:
                name: local_route
                virtual_hosts:
                - name: backend
                  domains: ["*"]
                  routes:
                  - match: { prefix: "/" }
                    route: { cluster: app }
              http_filters:
                - name: envoy.filters.http.router
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
      clusters:
      - name: app
        type: STATIC
        connect_timeout: 1s
        load_assignment:
          cluster_name: app
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  socket_address: { address: 127.0.0.1, port_value: 8888 }
      - name: spire_agent
        type: STATIC
        connect_timeout: 1s
        http2_protocol_options: {}
        load_assignment:
          cluster_name: spire_agent
          endpoints:
          - lb_endpoints:
            - endpoint:
                address:
                  pipe:
                    path: /run/spire/sockets/agent.sock
    admin:
      access_log_path: "/tmp/admin_access.log"
      address:
        socket_address: { address: 0.0.0.0, port_value: 9901 }

